START TRANSACTION;

ALTER TABLE QRTZ_JOB_DETAILS
  MODIFY COLUMN `JOB_NAME` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `JOB_GROUP` VARCHAR(190) NOT NULL;

ALTER TABLE QRTZ_TRIGGERS
  MODIFY COLUMN `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `JOB_NAME` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `JOB_GROUP` VARCHAR(190) NOT NULL;

ALTER TABLE QRTZ_SIMPLE_TRIGGERS
  MODIFY COLUMN `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `TRIGGER_GROUP` VARCHAR(190) NOT NULL;

ALTER TABLE QRTZ_CRON_TRIGGERS
  MODIFY COLUMN `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `TRIGGER_GROUP` VARCHAR(190) NOT NULL;

ALTER TABLE QRTZ_SIMPROP_TRIGGERS
  MODIFY COLUMN `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `TRIGGER_NAME` VARCHAR(190) NOT NULL;

ALTER TABLE QRTZ_BLOB_TRIGGERS
  MODIFY COLUMN `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `TRIGGER_GROUP` VARCHAR(190) NOT NULL;

ALTER TABLE QRTZ_CALENDARS
  MODIFY COLUMN `CALENDAR_NAME`  VARCHAR(190) NOT NULL;

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS
  MODIFY COLUMN `TRIGGER_GROUP`  VARCHAR(190) NOT NULL;

ALTER TABLE QRTZ_FIRED_TRIGGERS
  MODIFY COLUMN `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `JOB_NAME` VARCHAR(190) NULL,
  MODIFY COLUMN `JOB_GROUP` VARCHAR(190) NULL;

ALTER TABLE QRTZ_SCHEDULER_STATE
  MODIFY COLUMN `INSTANCE_NAME` VARCHAR(190) NOT NULL;

COMMIT;
